import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import SliceContainer from "./SliceContainer";
import HeaderSwiper from "./components/HeaderSwiper";
import FooterSection from "./components/Footer";
import Overlay from "./components/Overlay";
import LinksAside from "./components/LinksAside";
import DescriptionAside from "./components/DescriptionAside";
import DeliveryAside from "./components/DeliveryAside";
import ArrowUp from "./components/ArrowUp";
import ProductPreview from "./components/ProductPreview";
import { Toaster } from "react-hot-toast";
import StarterLoadingPage from "./components/StarterLoadingPage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Organic Farm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased hide`}
      >
        <SliceContainer>
          <StarterLoadingPage></StarterLoadingPage>
          <Toaster toastOptions={{
            position: "top-center",
            duration: 5000,
            success: {
              duration: 3000,
            }
          }}></Toaster>
          <ProductPreview></ProductPreview>
          <LinksAside></LinksAside>
          <DescriptionAside></DescriptionAside>
          <ArrowUp></ArrowUp>
          <DeliveryAside></DeliveryAside>
          <Overlay></Overlay>
          <Header></Header>
          <HeaderSwiper></HeaderSwiper>
          {children}
          <FooterSection></FooterSection>
        </SliceContainer>
      </body>
    </html>
  );
}
